# https://www.phind.com/search?cache=uw30a1s89jaw9t13lrqbq633
name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t tataran/docker-react -f Dockerfile.dev .

    - name: Run Tests
      run: docker run --rm -e CI=true tataran/docker-react npm run test -- --coverage
