# https://www.phind.com/search?cache=uw30a1s89jaw9t13lrqbq633
name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t tataran/docker-react -f Dockerfile.dev .

    - name: Run tests
      run: docker run -e CI=true tataran/docker-react npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Zip application code
      run: zip -r ${{ github.run_id }}.zip .

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-with-react
        environment_name: Docker-with-react-env
        region: ap-southeast-1
        version_label: ${{ github.run_id }}
        deployment_package: ${{ github.run_id }}.zip